CREATE SCHEMA IF NOT EXISTS "Teddy_360";

CREATE TABLE IF NOT EXISTS "Teddy_360".tarefas (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

